name       : libtirpc
version    : 1.0.1
release    : 2
source     :
    - http://internode.dl.sourceforge.net/project/libtirpc/libtirpc/1.0.1/libtirpc-1.0.1.tar.bz2 : 5156974f31be7ccbc8ab1de37c4739af6d9d42c87b1d5caf4835dda75fcbb89e
license    : BSD-3-Clause
summary    : RPC Library
component  : programming.library
description: |
    The libtirpc package contains libraries that support programs that use the Remote Procedure Call (RPC) API. It replaces the RPC, but not the NIS library entries that used to be in glibc.
builddeps  :
    - pkgconfig(com_err)
    - pkgconfig(krb5)
patterns   :
    - devel: /usr/share/man/man3
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
