name       : libtirpc
version    : 0.3.2
release    : 1
source     :
    - http://internode.dl.sourceforge.net/project/libtirpc/libtirpc/0.3.2/libtirpc-0.3.2.tar.bz2 : 2008a379f37f2c5d5a87a568b06707422cc3e4f5da305f7fb71f3f4c6d473ffc
license    : BSD-3-Clause
summary    : RPC Library
description: |
    The libtirpc package contains libraries that support programs that use the Remote Procedure Call (RPC) API. It replaces the RPC, but not the NIS library entries that used to be in glibc.
builddeps  :
setup      : |
    %configure --disable-gssapi --disable-static
build      : |
    %make
install    : |
    %make_install
