name       : libtirpc
version    : 1.3.2
release    : 10
source     :
    - https://kumisystems.dl.sourceforge.net/project/libtirpc/libtirpc/1.3.2/libtirpc-1.3.2.tar.bz2 : e24eb88b8ce7db3b7ca6eb80115dd1284abc5ec32a8deccfed2224fc2532b9fd
license    : BSD-3-Clause
summary    : RPC Library
component  : programming.library
description: |
    The libtirpc package contains libraries that support programs that use the Remote Procedure Call (RPC) API. It replaces the RPC, but not the NIS library entries that used to be in glibc.
builddeps  :
    - pkgconfig(com_err)
    - pkgconfig(krb5)
patterns   :
    - devel : /usr/share/man/man3
setup      : |
    %patch -p1 < $pkgfiles/0001-Use-vendor-config-files-as-fallback-for-a-stateless-.patch
    %reconfigure --disable-static
build      : |
    %make
install    : |
    %make_install
    install -m 00644 -D doc/netconfig $installdir/usr/share/defaults/etc/netconfig
    rm -rvf $installdir/etc
